### ISSUE TITLE
Exploring Best Practices for Light Mode and Other Enhancements

### ISSUE THREAD

**Issue by TSSFL** [fjosue4/google-gemini-ui#1]
Hi @fjosue4 

Thank you for creating the Google Gemini web chat interface https://github.com/fjosue4/google-gemini-ui. I have been thinking about something like this for a while and I really appreciate your great work!

I was thinking how to change the way an API Key is accessed by Google Generative AI Sample for Web https://github.com/google/generative-ai-js/tree/main/samples/web, just like it is done for ChatGPT at https://tssfl.com/viewtopic.php?t=6651 (see from original developer https://niek.github.io/chatgpt-web). I mean to make it possible for anyone to just copy and paste the key on the web interface rather than storing it in the back-end. Like you have done it.

I did not like the idea of accessing the API Key as an environment variable, see https://github.com/google/generative-ai-js/blob/main/samples/web/http-server.js.

You may find some other ideas to enhance the app, especially the UI by looking at these two sample web apps.

We are definitely excited to use your application.

**Comment by fjosue4** [comment]
Hi @TSSFL

Thanks for your suggestions, I'll take a look at your resources. I agree, that making the API process easier for more non-tech friendly users is important. 

Other users have already requested the Light Theme mode, and I've added it to the README as a requested feature.

**Comment by TSSFL** [comment]
@fjosue4 

Great!

**Comment by fjosue4** [comment]
Hello @TSSFL

I'm happy to tell you that the light mode is now available, just deployed a new version with that feature.

![image](https://github.com/fjosue4/google-gemini-ui/assets/85136931/c5761503-d06a-445c-b92a-c7c42113b32f)


Since the API thing won't be an easy win, I'll add it to the requested features and close this issue. Feel free to reopen or add a new one if you need to.

Thanks!
