### ISSUE TITLE
Thank you for your amazing work, but instead of putting your name, is it possible to make it put a forward proxy instead?

### ISSUE THREAD

**Issue by khfung** [fjosue4/google-gemini-ui#3]

**Comment by fjosue4** [comment]
Hey @khfung,

Sure thing, I'll keep the name since the idea is to add an initial prompt (not visible) welcoming you with your name which will also work as an API Key validator, but the name will remain optional so no worries. But I'll add a proxy option also optional, I'll try to handle this for today.

**Comment by fjosue4** [comment]
@khfung What's the expected URL you would like to point with a proxy?

`https://${proxy ? proxy + '.' : ''}generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`;

would it be a dot or a slash before the Google API?

**Comment by khfung** [comment]
Some of the country are not on the list of supporting country 
So, I would like to have a proxy to bypass regional restrictions
Like allowing user to put an api endpoint proxy instead of the default one

**Comment by fjosue4** [comment]
@khfung I added the proxy feature, as well as an example of what to add in that input. Let me know if that works.
