### ISSUE TITLE
I Cannot get the App to Display

### ISSUE THREAD

**Issue by TSSFL** [fjosue4/google-gemini-ui#6]
Hi @fjosue4 

I downloaded the app and put it in www.example.com/google-gemini, where google-gemini is an application, but I cannot get it to display. When I navigate to www.example.com/google-gemini, there is no error but the only thing I can see on the browser is the tittle of the page. What could be wrong ?

Thanks

**Comment by fjosue4** [comment]
Hey @TSSFL 
What deployment application do you use?
I usually handle my projects with [Vercel](https://vercel.com/) but Netlify should be a good option too.

**Comment by fjosue4** [comment]
If you don't use any of those, you can run: `npm run build`
<img width="458" alt="image" src="https://github.com/fjosue4/google-gemini-ui/assets/85136931/432927ec-99de-48f4-8aa8-c101138521b9">

And then you get the HTML, CSS and JS to upload and serve:
<img width="1438" alt="image" src="https://github.com/fjosue4/google-gemini-ui/assets/85136931/d72ab9fc-2d98-4cdb-9b85-06be07e520b8">

Make sure you have Node 18 or newer.

**Comment by TSSFL** [comment]
Hello @fjosue4 

Thank you very much for your insights. I was able to deploy the Gemini web chat on the live server. You can see the details of how I went through it in this post: https://www.tssfl.com/viewtopic.php?t=6778. I hope this helps anyone who wants to achieve the same.

Did you overwrite the light mode ? I seem not to find it in the master branch that I re-downloaded!

**Comment by TSSFL** [comment]
Future thought can be making it multi-modal web chat, with upload feature for images, see https://tssfl.com/gemini/, although currently does not work.

**Comment by fjosue4** [comment]
Awesome @TSSFL ! I'll link your documentation on the README if someone else needs to deploy differently than Vercel. 

The light mode is on the main branch. 
Check the component existing on main: https://github.com/fjosue4/google-gemini-ui/tree/main/src/components/ThemeToggle

---------------


About using the image API, you'll need to modify line 12 on this file: https://github.com/fjosue4/google-gemini-ui/blob/main/src/store/user/dispatchers.user.ts

https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=

Instead of Gemini Pro, you need to use [Gemini Pro Vision](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini?hl=es-419#gemini-pro-vision)

The current API used only accepts text prompts, you'll need to use

**Comment by fjosue4** [comment]
I think you handled the Light mode, tested and worked on your website: 
![image](https://github.com/fjosue4/google-gemini-ui/assets/85136931/fcb1de89-35a6-4630-98b0-3a4161d9b05b)

**Comment by fjosue4** [comment]
@TSSFL Let me know if we're good to close this issue or feel free to close it. You can open a new one if you need additional help in other topic or if there's a bug :D

**Comment by TSSFL** [comment]
Hi @fjosue4

Thank you very much. To this point it suffices to close this issue. I'm closing it.
